name: 'EIDUEvents'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'EIDU'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# directories to be removed by `dbt clean`
clean-targets:         
  - "target"
  - "dbt_packages"
  - "logs"

on-run-start:
    - "CREATE SCHEMA IF NOT EXISTS prepared_data"
    - "CREATE SCHEMA IF NOT EXISTS transformed_data"

models:
  staging:
    +database: "challenge_suganthi"
    +schema: "prepared_data"
    +materialized: view
    +tags: ["kenya", "prepared", "log_events"]

  marts:
    +database: "challenge_suganthi"
    +schema: "transformed_data"
    +materialized: table
    +tags: ["kenya", "transformed", "bi"]