# This is a basic workflow to help you get started with Actions

name: CI/CD
run-name: Seggregating and Analysing EIDU Events logs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:


  transformation_dbt:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dbt-labs/dbt-redshift:1.5.10
    
    steps:
      - uses: actions/checkout@v4

      - name: dbt initialize
        run: |
          dbt --version
          mv transform_data/dbt_profile.yml transform_data/profiles.yml
          
      - name: dbt test connection
        run: dbt debug --project-dir transform_data --profiles-dir transform_data --profile EIDU

      - name: dbt slim run if manifest file exists
        if: "${{ hashFiles('dbt_run_artifacts/manifest.json') != '' }}"
        run: |
          echo "Dbt run state file exits"
          dbt compile --project-dir transform_data --profiles-dir transform_data 
          echo "DBT executing only modified models"
          cd transform_data
          cat dbt_project.yml
          cat profiles.yml
          dbt run --profiles-dir .. --project-dir . --select state:modified+ --defer --state dbt_run_artifacts 
      
      - name: dbt full run if no manifest file
        if: "! ${{ hashFiles('dbt_run_artifacts/manifest.json') != '' }}"
        run: |
          echo "DBT run state file not found"
          echo "DBT executing all models"
          dbt run --project-dir transform_data --profiles-dir transform_data

      - name: git commit DBT state file
        run: |
          mkdir -p dbt_run_artifacts
          cp -f transform_data/target/manifest.json dbt_run_artifacts/manifest.json
          git config --global --add safe.directory $(realpath .)
          git config user.name github-actions
          git config user.email github-actions@eidu.com
          git add dbt_run_artifacts/manifest.json
          git commit -m "Adding/Updating Dbt state file"
          git push



    
