# This is a basic workflow to help you get started with Actions

name: CI/CD
run-name: Seggregating and Analysing EIDU User Behaviour Events

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  load_datasets:
    runs-on: ubuntu-latest
    container: 
      image: python:3.9-slim-bookworm

    steps:
      - uses: actions/checkout@v4

      - name: install python packages
        run: |
          python -m pip install -q --upgrade pip
          pip install -r  -q load_data/py_requirements.txt

      - name: execute load script
        run: python load_data/load_dataset_to_redshift.py

  transformation_compile:
    runs-on: ubuntu-latest
    needs: [load_datasets]
    container:
      image: ghcr.io/dbt-labs/dbt-redshift:1.5.10
    
    steps:
      - uses: actions/checkout@v4

      - name: dbt initialize
        run: |
          dbt --version
          mv transform_data/dbt_profile.yml transform_data/profiles.yml
          
      - name: dbt test connection
        run: dbt debug --project-dir transform_data --profiles-dir transform_data --profile EIDU



    
