# This is a basic workflow to help you get started with Actions

name: CI/CD
run-name: Seggregating and Analysing EIDU Events logs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  load_datasets:
    runs-on: ubuntu-latest
    container: 
      image: python:3.9-slim-bookworm

    steps:
      - uses: actions/checkout@v4

      - name: install python packages
        run: |
          python -m pip config --quiet set global.disable-pip-version-check true
          python -m pip install --quiet --user --requirement load_data/py_requirements.txt
          echo "Installed Packages Successfully" ; cat load_data/py_requirements.txt

      - name: execute load script
        run: python load_data/load_data_to_redshift.py

  transformation_compile:
    runs-on: ubuntu-latest
    needs: [load_datasets]
    container:
      image: ghcr.io/dbt-labs/dbt-redshift:1.5.10
    
    steps:
      - uses: actions/checkout@v4

      - name: dbt initialize
        run: |
          dbt --version
          mv transform_data/dbt_profile.yml transform_data/profiles.yml
          
      - name: dbt test connection
        run: dbt debug --project-dir transform_data --profiles-dir transform_data --profile EIDU

      - name: check commit
        run: |
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add generated.txt
          git commit -m "generated"
          git push



    
